version: '3'
services:
    apache:
        build:
            context: ./.docker
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
            - ./.docker/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - apiworksign-net
        depends_on:
            - db
    db:
        image: 'mariadb:10'
        ports:
            - '3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=worksignDatabase
            - MYSQL_USER=worksign_user
            - MYSQL_PASSWORD=worksignpassword
        volumes:
            - 'dbdata:/var/lib/mysql'
        networks:
            - apiworksign-net
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_HOST=db
          - PMA_USER=root
          - PMA_PASSWORD=root
          - MYSQL_ROOT_PASSWORD=root
        ports:
        - 8081:80
        networks:
          - apiworksign-net
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025'
            - '8082:8025'
        networks:
            - apiworksign-net
networks:
    apiworksign-net:
        driver: bridge
volumes:
    dbdata:
        driver: local
